/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\atril.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';


export default function Model(props) {
  const { nodes, materials } = useGLTF('/atril.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={10} position={[0, -0.5, 0]} rotation={[0.5,-2,0]}>
      <mesh geometry={nodes.pCube1.geometry} material={materials.standardSurface1} rotation={[Math.PI / 2, 0, 0]} scale={[0.037, 0.037, 0.009]} />
    </group>
  )
}

useGLTF.preload('/atril.glb')
