/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\ayuntamiento.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ayuntamiento.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={0.8} position={[0, 0, 0]}>
      <mesh geometry={nodes.ayuntamiento.geometry} material={materials.standardSurface1} rotation={[Math.PI / 2, 0, -1.602]} scale={0.01}>
        <mesh geometry={nodes.barandillaArriba.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.baseayuntamiento.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.baseTorre1.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.bordillotorre.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.bordillotorre1.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.bordillotorre2.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.bordillotorre3.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.bordillotorre4.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.bordillotorre5.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.cupula1.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.cupula2.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.cupula3.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.decobarandilla.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.decobarandilla1.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla002.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla11001.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla018.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla12.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla011.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla13.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla012.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla14.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla013.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla15.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla014.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla16.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla015.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.pirulibarandilla1.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla17.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla016.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla18.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla019.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla19.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla020.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.pirulibarandilla2.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla2.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla003.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla20.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla021.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.pirulibarandilla1001.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla21.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla022.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.pirulibarandilla2001.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla22.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla026.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla23.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla024.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla24.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla017.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla25.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla027.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla26.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla023.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla27.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla025.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla3.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla004.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla4.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla005.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla5.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla006.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla6.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla007.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla7.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla008.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla8.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla009.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decobarandilla9.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.pirulibarandilla010.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pirulibarandilla001.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.decopared.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.decopared10.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared11.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared12.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared13.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared14.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared15.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared16.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared17.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared18.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared19.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared2.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared20.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared21.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared22.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared23.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.decobarandilla11.geometry} material={materials.standardSurface1}>
              <mesh geometry={nodes.pirulibarandilla.geometry} material={materials.standardSurface1} />
            </mesh>
            <mesh geometry={nodes.pilar22.geometry} material={materials.standardSurface1}>
              <mesh geometry={nodes.cuadradopilar2011.geometry} material={materials.standardSurface1} />
              <mesh geometry={nodes.cuadradopilar3011.geometry} material={materials.standardSurface1} />
            </mesh>
            <mesh geometry={nodes.pilar23.geometry} material={materials.standardSurface1}>
              <mesh geometry={nodes.cuadradopilar2010.geometry} material={materials.standardSurface1} />
              <mesh geometry={nodes.cuadradopilar3010.geometry} material={materials.standardSurface1} />
            </mesh>
            <mesh geometry={nodes.triangulo8.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.decopared24.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared25.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared26.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared27.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared28.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared29.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared3.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared30.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared31.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared32.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared33.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared34.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared35.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared36.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared37.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared38.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared39.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared4.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared40.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared41.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared42.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared43.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared44.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared45.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared46.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared47.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared48.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared49.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared5.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared50.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared51.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared52.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared54.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared55.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared56.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared57.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared58.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared6.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared7.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared8.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopared9.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.torre9.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.decopuerta.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.decopuerta2.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopuerta3.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopuerta4.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopuerta5.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopuerta6.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopuerta7.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.decopuerta8.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.decoracionesCuadradas.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.cuadradopilar10.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar11.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar12.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar13.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar14.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar15.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar16.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar5.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar6.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar7.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar9.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.pilar11Ventanas.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.cuadradopilar006.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar2006.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar3006.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.pilar12.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar009.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2009.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3009.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar13.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar008.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2008.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3008.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar14.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar007.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2007.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3007.geometry} material={materials.standardSurface1} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.pilar16.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.cuadradopilar010.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar2012.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar3012.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.pilar17.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar013.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2015.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3015.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar18.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar012.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2014.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3014.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar19.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar011.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2013.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3013.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar20.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2017.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3017.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar21.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2016.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3016.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar22001.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2023.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3023.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar23001.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2022.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3022.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar24.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2018.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3018.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.pilar25.geometry} material={materials.standardSurface1}>
              <mesh geometry={nodes.cuadradopilar2019.geometry} material={materials.standardSurface1} />
              <mesh geometry={nodes.cuadradopilar3019.geometry} material={materials.standardSurface1} />
            </mesh>
          </mesh>
          <mesh geometry={nodes.pilar26.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.pilar27.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.pilar28.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.pilar29.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.pilar31.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.pilar32.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2029.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3029.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar33.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2032.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3032.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar34.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2024.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3024.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar35.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2021.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3021.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar36.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2020.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3020.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar37.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2027.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3027.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar38.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2028.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3028.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar39.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2025.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3025.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar40.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2026.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3026.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar41.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2030.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3030.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar42.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar2031.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3031.geometry} material={materials.standardSurface1} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.pilaresENTRADA.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.cuadradopilar.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar2.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.cuadradopilar3.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.pilar10.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3001.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar6.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar005.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2005.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3005.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar7.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar004.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2004.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3004.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar8.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar003.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2003.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3003.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.pilar9.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.cuadradopilar002.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar2002.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.cuadradopilar3002.geometry} material={materials.standardSurface1} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.puertaPrincipal.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.relieve1ayntamiento.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.relieveArribaAyuntamiento.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.relieveBaseayuntamiento.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.relieveBaseTorre2.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.relieveBasetorre3.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.relievetorre5.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.reloj.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.pilar30.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.reloj1.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.reloj2.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.semicirculo1.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.semicirculo3.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.semicirculo4.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.semicirculo5.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.semicirculo6.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.semicirculo7.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.semicirculo8.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.torre6.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.torre7.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.torre8.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.triangulo.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.triangulo10.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo11.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo12.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo13.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo14.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo15.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo2.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo4.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo5.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo6.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo7.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.triangulo8001.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.trienagulo3.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.vallaArriba.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.valla1.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla10.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1002.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2002.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3002.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6002.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7002.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla11.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1003.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2003.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3003.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6003.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7003.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla12.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1004.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2004.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3004.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla5001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6004.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7004.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla14.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1005.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2005.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3005.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6005.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7005.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla2.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla3.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla5.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla6.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla7.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla8.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7001.geometry} material={materials.standardSurface1} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.vallaBalconprincipal.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.barandilla4.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla1013.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla2013.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla20.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla21.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla22.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla23.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla24.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla25.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla26.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla27.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla28.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla29.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla3013.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla30.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla31.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla32.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla33.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla34.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla35.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla36.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla37.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla38.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla39.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla40.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla41.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla6013.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla7015.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.VallasBalcones2.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.barandilla10.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.barandilla11.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.barandilla2.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.barandilla3.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.barandilla5.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.barandilla6.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.barandilla7.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.barandilla8.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.barandilla9.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla15.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla16.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla17.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla16001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla18.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla58.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7007.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla42.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1006.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2006.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3006.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6006.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7008.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla43.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1007.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2007.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3007.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla49.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla50.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6007.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7009.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla44.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1008.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2008.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3008.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla45.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla46.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla48.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6008.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7010.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla51.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1009.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2009.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3009.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6009.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7011.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla52.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1010.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2010.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3010.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla49001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla50001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6010.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7012.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla53.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1011.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2011.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3011.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla45001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla46001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla48001.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6011.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7013.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla54.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.valla1012.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla2012.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla3012.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla55.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla56.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla6012.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.valla7014.geometry} material={materials.standardSurface1} />
          </mesh>
          <mesh geometry={nodes.valla57.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.valla7006.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.ventana.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.ventana1.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana10.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana11.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana12.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana13.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana14.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana15.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana16.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana17.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana18.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana2.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana3.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana4.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana5.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana6.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana7.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana8.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ventana9.geometry} material={materials.standardSurface1} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/ayuntamiento.glb')
