/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\banco.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/banco.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group position={[-0.5, -0.1, 0]} rotation={[Math.PI / 2, 0, 111]} scale={0.02}>
        <mesh geometry={nodes.Body43.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body44.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body45.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body46.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body47.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body48.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body49.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body50.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body51.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body52.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body53.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body54.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body55.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body56.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body57.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body58.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body59.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body60.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body61.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body62.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body63.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.pata1.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['pata1_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.pata2.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['pata2_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.pata4.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['pata4_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.pata5.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['pata5_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.pata8.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['pata8_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['pata8_(1)_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['pata8_(2)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.pata9.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['pata9_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/banco.glb')
