/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\cajaHerramientas.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cajaHerramientas.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={5} position={[0, 0, 0]} rotation={[0,0,0]}>
      <mesh geometry={nodes.cajaHerramientas.geometry} material={materials['standardSurface1.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.cajon.geometry} material={materials['standardSurface1.004']} />
        <mesh geometry={nodes.tapa.geometry} material={materials['standardSurface1.004']}>
          <mesh geometry={nodes.asa.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.hierroabajo.geometry} material={materials['standardSurface1.004']}>
            <mesh geometry={nodes.hierro.geometry} material={materials['standardSurface1.004']} />
            <mesh geometry={nodes.hierroarriba.geometry} material={materials['standardSurface1.004']} />
            <mesh geometry={nodes.tornillo.geometry} material={materials['standardSurface1.004']} />
            <mesh geometry={nodes.tornillo2.geometry} material={materials['standardSurface1.004']} />
            <mesh geometry={nodes.tornillo3.geometry} material={materials['standardSurface1.004']} />
            <mesh geometry={nodes.tornillo4.geometry} material={materials['standardSurface1.004']} />
            <mesh geometry={nodes.tornillo5.geometry} material={materials['standardSurface1.004']} />
          </mesh>
          <mesh geometry={nodes.tornillo10.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.tornillo11.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.tornillo12.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.tornillo13.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.tornillo14.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.tornillo15.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.tornillo6.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.tornillo7.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.tornillo8.geometry} material={materials['standardSurface1.004']} />
          <mesh geometry={nodes.tornillo9.geometry} material={materials['standardSurface1.004']} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/cajaHerramientas.glb')
