/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\carretilla.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';


export default function Model(props) {
  const { nodes, materials } = useGLTF('/carretilla.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={18} position={[0, -0.6, 0]}>
      <group position={[0, 0, 0.028]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.pCube10.geometry} material={materials['standardSurface1.002']} position={[0.977, -4.779, -0.399]} scale={[0.066, 0.612, 0.411]} />
        <mesh geometry={nodes.pCube12.geometry} material={materials['standardSurface1.002']} position={[-0.923, -4.934, -0.285]} rotation={[0, 0, Math.PI]} scale={[0.072, 0.838, 0.292]} />
        <mesh geometry={nodes.pCube13.geometry} material={materials['standardSurface1.002']} position={[-0.86, -3.304, -0.467]} scale={[0.813, 5.849, 0.315]} />
        <mesh geometry={nodes.pCube14.geometry} material={materials['standardSurface1.002']} position={[-0.776, -4.934, -0.285]} scale={[0.072, 0.838, 0.292]} />
        <mesh geometry={nodes.pCube15.geometry} material={materials['standardSurface1.002']} position={[-0.742, -4.779, -0.399]} scale={[0.066, 0.612, 0.411]} />
        <mesh geometry={nodes.pCube2.geometry} material={materials['standardSurface1.002']} position={[0, -0.706, -1.036]} scale={[2.633, 0.591, 1.433]} />
        <mesh geometry={nodes.pCube7.geometry} material={materials['standardSurface1.002']} position={[0.943, -4.934, -0.285]} scale={[0.072, 0.838, 0.292]} />
        <mesh geometry={nodes.pCube8.geometry} material={materials['standardSurface1.002']} position={[0.859, -3.304, -0.467]} scale={[0.813, 5.849, 0.315]} />
        <mesh geometry={nodes.pCube9.geometry} material={materials['standardSurface1.002']} position={[0.796, -4.934, -0.285]} rotation={[0, 0, Math.PI]} scale={[0.072, 0.838, 0.292]} />
        <mesh geometry={nodes.polySurface2.geometry} material={materials['standardSurface1.002']} position={[0, 0.528, -0.908]} scale={[0.483, 0.81, 0.483]} />
        <mesh geometry={nodes.polySurface3.geometry} material={materials['standardSurface1.002']} position={[0, 0.528, -0.908]} scale={[0.483, 0.81, 0.483]} />
        <mesh geometry={nodes.polySurface4.geometry} material={materials['standardSurface1.002']} position={[0, 0.528, -0.908]} scale={[0.483, 0.81, 0.483]} />
        <mesh geometry={nodes.polySurface5.geometry} material={materials['standardSurface1.002']} position={[0, 0.528, -0.908]} scale={[0.483, 0.81, 0.483]} />
        <mesh geometry={nodes.pPipe1.geometry} material={materials['standardSurface1.002']} position={[0.553, 0.339, -0.438]} rotation={[0, -1.571, 0]} scale={[0.386, 0.386, 0.274]} />
        <mesh geometry={nodes.pPipe2.geometry} material={materials['standardSurface1.002']} position={[-0.554, 0.339, -0.438]} rotation={[0, -1.571, 0]} scale={[0.359, 0.359, 0.255]} />
        <mesh geometry={nodes.pPipe5.geometry} material={materials['standardSurface1.002']} position={[0.866, -4.609, -0.277]} rotation={[0, -1.571, 0]} scale={[0.237, 0.237, 0.169]} />
        <mesh geometry={nodes.pPipe6.geometry} material={materials['standardSurface1.002']} position={[0.866, -5.219, -0.277]} rotation={[0, -1.571, 0]} scale={[0.237, 0.237, 0.169]} />
        <mesh geometry={nodes.pPipe7.geometry} material={materials['standardSurface1.002']} position={[-0.853, -4.609, -0.277]} rotation={[0, -1.571, 0]} scale={[0.237, 0.237, 0.169]} />
        <mesh geometry={nodes.pPipe8.geometry} material={materials['standardSurface1.002']} position={[-0.853, -5.219, -0.277]} rotation={[0, -1.571, 0]} scale={[0.237, 0.237, 0.169]} />
      </group>
    </group>
  )
}

useGLTF.preload('/carretilla.glb')
