/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\cuboPintura.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cuboPintura.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={5} position={[0, -0.4, 0]} rotation={[0,0,0]}>
      <group position={[0.002, 0, 0]} rotation={[0.386, 1.299, -0.335]} scale={0.001}>
        <mesh geometry={nodes.Body1.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body2.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body3.geometry} material={materials['Steel - Satin']} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/cuboPintura.glb')
