/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\edificio2def.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


export default function Model(props) {
  const { nodes, materials } = useGLTF('/edificio2def.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={0.9} position={[0, -0.1, 0]}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.prova1pCube25.geometry} material={materials.lambert1} position={[-53.626, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube26.geometry} material={materials.lambert1} position={[-41.547, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube27.geometry} material={materials.lambert1} position={[-22.684, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube28.geometry} material={materials.lambert1} position={[-34.764, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube29.geometry} material={materials.lambert1} position={[-2.52, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube30.geometry} material={materials.lambert1} position={[-14.6, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube31.geometry} material={materials.lambert1} position={[16.343, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube32.geometry} material={materials.lambert1} position={[4.263, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube33.geometry} material={materials.lambert1} position={[35.205, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube34.geometry} material={materials.lambert1} position={[23.126, 25.776, -24.749]} scale={[1.351, 1, 70.272]} />
        <mesh geometry={nodes.prova1pCube5.geometry} material={materials.lambert1} position={[-9.721, 0, 0]} scale={[107.839, 52.224, 126.374]} />
        <mesh geometry={nodes.prova1polySurface113.geometry} material={materials['prova1:standardSurface2']} position={[-32.056, 130.374, -34.91]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.prova1polySurface130.geometry} material={materials['prova1:standardSurface2']} position={[-32.472, 130.374, -61.221]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.prova1polySurface147.geometry} material={materials['prova1:standardSurface2']} position={[-32.472, 94.791, -61.221]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.prova1polySurface164.geometry} material={materials['prova1:standardSurface2']} position={[-32.056, 94.791, -34.91]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.prova1polySurface190.geometry} material={materials.lambert1} position={[1596.763, -1027.677, 389.697]} scale={[34.67, 48.601, 10.008]} />
        <mesh geometry={nodes.prova1polySurface45.geometry} material={materials['prova1:standardSurface2']} position={[89.656, 130.374, -34.91]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.prova1polySurface62.geometry} material={materials['prova1:standardSurface2']} position={[89.656, 94.791, -34.91]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.prova1polySurface79.geometry} material={materials['prova1:standardSurface2']} position={[89.656, 94.791, -61.221]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.prova1polySurface96.geometry} material={materials['prova1:standardSurface2']} position={[89.656, 130.374, -61.221]} rotation={[0, 0, Math.PI / 2]} />
      </group>
      <mesh geometry={nodes.prova1polySurface39001.geometry} material={materials.lambert1} position={[3.44, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.prova1Cuerpo11001.geometry} material={materials.lambert1} position={[3.44, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.prova1polySurface189001.geometry} material={materials.lambert1} position={[3.44, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.prova1ventana45001.geometry} material={materials['prova1:standardSurface2']} position={[3.44, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[3.44, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh028.geometry} material={materials['prova1:standardSurface2']} />
        <mesh geometry={nodes.Mesh028_1.geometry} material={materials.lambert1} />
      </group>
    </group>
  )
}

useGLTF.preload('/edificio2def.glb')
