/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\escalera.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';


export default function Model(props) {
  const { nodes, materials } = useGLTF('/escalera.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={10} position={[0, -0.65, 0]}>
      <group position={[0.005, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.pCube32.geometry} material={materials['standardSurface1.003']} position={[1.943, -1.46, -6.475]} rotation={[0, 0.294, 0]} scale={[0.411, 0.418, 13.517]} />
        <mesh geometry={nodes.pCube34.geometry} material={materials['standardSurface1.003']} position={[1.943, 0.907, -6.475]} rotation={[0, 0.294, 0]} scale={[0.411, 0.418, 13.517]} />
        <mesh geometry={nodes.pCube36.geometry} material={materials['standardSurface1.003']} position={[3.754, -0.169, -0.533]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube37.geometry} material={materials['standardSurface1.003']} position={[3.451, -0.169, -1.583]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube38.geometry} material={materials['standardSurface1.003']} position={[3.167, -0.169, -2.577]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube39.geometry} material={materials['standardSurface1.003']} position={[2.883, -0.169, -3.609]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube40.geometry} material={materials['standardSurface1.003']} position={[2.599, -0.169, -4.565]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube41.geometry} material={materials['standardSurface1.003']} position={[2.306, -0.169, -5.596]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube42.geometry} material={materials['standardSurface1.003']} position={[2.022, -0.169, -6.618]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube43.geometry} material={materials['standardSurface1.003']} position={[1.728, -0.169, -7.622]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube44.geometry} material={materials['standardSurface1.003']} position={[1.425, -0.169, -8.672]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube45.geometry} material={materials['standardSurface1.003']} position={[1.151, -0.169, -9.628]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube46.geometry} material={materials['standardSurface1.003']} position={[0.876, -0.169, -10.641]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube47.geometry} material={materials['standardSurface1.003']} position={[0.583, -0.169, -11.625]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCube48.geometry} material={materials['standardSurface1.003']} position={[0.346, -0.169, -12.477]} rotation={[0, 0.28, 0]} scale={[0.4, 2.351, 0.179]} />
        <mesh geometry={nodes.pCylinder13.geometry} material={materials['standardSurface1.003']} position={[0, 0, -6.488]} rotation={[-Math.PI, 1.566, -Math.PI]} scale={[0.017, 0.017, 2.016]} />
      </group>
    </group>
  )
}

useGLTF.preload('/escalera.glb')
