/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\espatula.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/espatula.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={3.7} position={[0, 0, 0]} rotation={[0,0,0]}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Body1.geometry} material={materials['Steel - Satin.003']} scale={10} />
        <mesh geometry={nodes.Body3.geometry} material={materials['Steel - Satin.003']} scale={10} />
        <mesh geometry={nodes.Body4.geometry} material={materials['Steel - Satin.003']} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/espatula.glb')
