/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\falla_low1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/falla_low1.glb')
  return (
    <group {...props} dispose={null} scale={0.15}>
      <mesh geometry={nodes.Fallacartoon.geometry} material={materials.Cable_2} position={[-0.5, 2.5, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/falla_low1.glb')
