/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\Farola.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Farola.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cuerpo.geometry} material={materials['Steel - Satin']} scale={10} />
      <mesh geometry={nodes.Ramas.geometry} material={materials['Steel - Satin']} scale={10} />
      <mesh geometry={nodes.Lámpara2.geometry} material={materials['Steel - Satin']} scale={10} />
      <mesh geometry={nodes.Lámpara3.geometry} material={materials['Steel - Satin']} scale={10} />
      <mesh geometry={nodes.Lámpara1.geometry} material={materials['Steel - Satin']} scale={10} />
    </group>
  )
}

useGLTF.preload('/Farola.gltf')
