/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\grupoCajas.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';


export default function Model(props) {
  const { nodes, materials } = useGLTF('/grupoCajas.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={10} position={[0, -0.5, 0]}>
      <group position={[0.039, 0, 0.007]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.pasted__pCube3.geometry} material={materials.standardSurface1} position={[-0.068, 0, -2]} rotation={[0, -1.571, 0]} scale={[3.238, 3.238, 12.691]} />
        <mesh geometry={nodes.pasted__pCube4.geometry} material={materials.standardSurface1} position={[-6.152, 3.837, -2]} rotation={[Math.PI / 2, -0.965, Math.PI / 2]} scale={[3.238, 3.238, 6.562]} />
        <mesh geometry={nodes.pCube4.geometry} material={materials.standardSurface1} position={[-0.486, 1.75, -5.055]} rotation={[Math.PI / 2, 0.801, -Math.PI / 2]} scale={[2.849, 2.849, 8.322]} />
        <mesh geometry={nodes.pCube5.geometry} material={materials.standardSurface1} position={[-2.006, 0.814, -4.854]} rotation={[0, 0, 0.573]} scale={3.143} />
        <mesh geometry={nodes.pCube6.geometry} material={materials.standardSurface1} position={[-4.923, 2.895, -7.822]} rotation={[0, 0, 0.573]} scale={2.662} />
        <mesh geometry={nodes.pCube7.geometry} material={materials.standardSurface1} position={[-4.518, -3.585, -5.479]} rotation={[0, 1.571, 0]} scale={[11.039, 2.514, 3.834]} />
        <mesh geometry={nodes.pCube8.geometry} material={materials.standardSurface1} position={[0.665, 4.49, -2]} rotation={[0, 0, 0.233]} scale={[4, 3.046, 3.575]} />
      </group>
    </group>
  )
}

useGLTF.preload('/grupoCajas.glb')
