/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\LogoPlantea.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelLogoPlantea(props) {
  const { nodes, materials } = useGLTF('/LogoPlantea.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cuerpo.geometry} material={materials.standardSurface1}>
        <mesh geometry={nodes.OJO.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.OJO2.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.boquita.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pierna1.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.CALECETIN1.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.ZAPATP1.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.pierna2.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.ZAPATO2.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.CALCETIN2.geometry} material={materials.standardSurface1} />
        </mesh>
        <mesh geometry={nodes.brazo2.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.DEDO4.geometry} material={materials.standardSurface1}>
            <mesh geometry={nodes.DEDO6.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.DEDO5.geometry} material={materials.standardSurface1} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.BRAZO.geometry} material={materials.standardSurface1}>
          <mesh geometry={nodes.DEDO1.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.DEDO2.geometry} material={materials.standardSurface1} />
          <mesh geometry={nodes.DEDO3.geometry} material={materials.standardSurface1} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/LogoPlantea.gltf')
