/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\mesaTaller.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mesaTaller.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={1.5} position={[0, 0, 0]} rotation={[0,0,0]}>
      <mesh geometry={nodes.mesa.geometry} material={materials['standardSurface1.001']} position={[0, 0.219, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.5, 0.047]}>
        <mesh geometry={nodes.mesa1.geometry} material={materials['standardSurface1.001']} position={[0, 0, 5.85]} scale={[0.877, 0.819, 0.635]} />
        <mesh geometry={nodes.pata2.geometry} material={materials['standardSurface1.001']} position={[-0.447, 0.382, 5.108]} scale={[0.05, 0.1, 10.584]} />
        <mesh geometry={nodes.pata6.geometry} material={materials['standardSurface1.001']} position={[-0.447, -0.374, 5.108]} scale={[0.05, 0.1, 10.584]} />
        <mesh geometry={nodes.pata7.geometry} material={materials['standardSurface1.001']} position={[0.437, 0.382, 5.108]} scale={[0.05, 0.1, 10.584]} />
        <mesh geometry={nodes.pata8.geometry} material={materials['standardSurface1.001']} position={[0.437, -0.374, 5.108]} scale={[0.05, 0.1, 10.584]} />
        <mesh geometry={nodes.pCube3.geometry} material={materials['standardSurface1.001']} position={[0.435, 0.01, 3.009]} rotation={[0.139, 0, 0]} scale={[0.01, 0.111, 5.509]} />
        <mesh geometry={nodes.pCube4.geometry} material={materials['standardSurface1.001']} position={[-0.448, 0.01, 3.009]} rotation={[-0.139, 0, 0]} scale={[0.01, 0.111, 5.509]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/mesaTaller.glb')
