/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\taburete.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/taburete.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={3} position={[0, -0.5, 0]} rotation={[0,0,0]}>
      <group rotation={[0.021, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Body1.geometry} material={materials['Steel - Satin.001']} scale={10} />
        <mesh geometry={nodes.Body11.geometry} material={materials['Steel - Satin.001']} scale={10} />
        <mesh geometry={nodes.Body13.geometry} material={materials['Steel - Satin.001']} scale={10} />
        <mesh geometry={nodes.Body14.geometry} material={materials['Steel - Satin.001']} scale={10} />
        <mesh geometry={nodes.Body2.geometry} material={materials['Steel - Satin.001']} scale={10} />
        <mesh geometry={nodes.Body6.geometry} material={materials['Steel - Satin.001']} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/taburete.glb')
