/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\vallaAmarilla.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';


export default function Model(props) {
  const { nodes, materials } = useGLTF('/vallaAmarilla.glb')
  const groupRef = useRef();
  useFrame(() => {
    // Aquí puedes actualizar la rotación del modelo
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Por ejemplo, rota en el eje Y a una velocidad de 0.01 radianes por fotograma
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={4} position={[0, 0, 0]} rotation={[0,0,0]}>
      <mesh geometry={nodes.VAYA.geometry} material={materials.standardSurface1} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.pCube10.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCube11.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCube12.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCube9.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder11.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder12.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder13.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder14.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder15.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder16.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder17.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder18.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder19.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder8.geometry} material={materials.standardSurface1} />
        <mesh geometry={nodes.pCylinder9.geometry} material={materials.standardSurface1} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/vallaAmarilla.glb')
